### ISSUE TITLE
1.1.15 calls non existing function

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/storefront-sticky-add-to-cart#12]
In version 1.1.15 the following code was changed from:

```
$product->get_rating_html()
```

to:

```
wc_get_rating_html( $product->get_average_rating()
```

The function `wc_get_rating_html` is not present in WooCommerce 2.6 this will only be included in 3.0
Would need to add some version checking to make sure it is calling the correct code.

Affected ticket: 545662-zd-woothemes

**Comment by jobthomas** [comment]
@jameskoster I've had the same error with one of my own dogfeeding sites.

**Comment by jameskoster** [comment]
Fixed and deployed!
