### ISSUE TITLE
Waypoint conflict with Visual Composer

### ISSUE THREAD

**Issue by cyberwani** [woocommerce/storefront-sticky-add-to-cart#14]
Hi,
I am using Visual Composer, and when I'm scrolling page, sticky-add-to-cart is not displaying. After checking I found that Visual Composer is also using Waypoint, which is too old than used in sticky-add-to-cart. VC is using v2.0.2, while sticky-add-to-cart is using v4.0.0.

**Comment by jameskoster** [comment]
You should probably take up this issue with VC if updating to the latest version of the Waypoint script fixes the issue :)
