### ISSUE TITLE
Conflict with WooCommerce Waitlist

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/storefront-sticky-add-to-cart#15]
#### Affected tickets

708705-zen

#### What I expected

To use both plugins on one site (Storefront Sticky Add to Cart, and WooCommerce Waitlist)

#### What happened instead

The WooCommerce Waitlist plugin hooks onto the `woocommerce_get_availability` to add its extra message about signing up to the waitlist. Unfortunately, this is triggered here:

https://github.com/woocommerce/storefront-sticky-add-to-cart/blob/master/storefront-sticky-add-to-cart.php#L278

And passed through HTML sanitizer, to give broken HTML code like here:

![Screenshot](http://cld.wthms.co/L3f5MV+)
Screenshot: http://cld.wthms.co/L3f5MV

#### Steps to reproduce 

1. Download and install WooCommerce Waitlist: https://woocommerce.com/products/woocommerce-waitlist/
2. Enable Sticky Add to Cart Header
3. Add a product that's out of stock
4. Observe the product page

**Comment by jameskoster** [comment]
@tiagonoronha would you be able to look at this one?

**Comment by neilpie** [comment]
@tiagonoronha @jameskoster 

Is this something that we need to handle from within WCWL? I believe that we may have had to deal with a similar issue previously

**Comment by jameskoster** [comment]
No that's ok, we're just escaping too hard [here](https://github.com/woocommerce/storefront-sticky-add-to-cart/blob/master/storefront-sticky-add-to-cart.php#L280).

I'll look at fixing this quickly just now.

**Comment by jameskoster** [comment]
OK I fixed this, but I did notice some js errors that you might want to look into @neilpie - your call.

So, this plugin looks at the position of `form.cart` to decide when to reveal the "sticky add to cart" component. However, that element isn't present on simple products that are out of stock. I've fixed the code to check whether that element exists before running, but if you want the "Join waitlist" button / message to be sticky you should consider wrapping in that element / class. Like I said, totally up to you :)
