### ISSUE TITLE
Sticky cart no longer showing

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/storefront-sticky-add-to-cart#16]
Ticket: 764759-zen

There are also multiple reports in the forums: 
https://wordpress.org/plugins/storefront-sticky-add-to-cart/#reviews

I tested this on my dev site and also wasn't able to get it working - the sticky cart header never shows up on the product page.

`
### WordPress Environment ###

Home URL: https://woodev.mystagingwebsite.com
Site URL: https://woodev.mystagingwebsite.com
WC Version: 3.2.1

### Active Plugins (5) ###

Storefront Sticky Add to Cart: by WooThemes – 1.1.7
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.7
WooCommerce Warranty Requests: by WooCommerce – 1.8.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1

### Theme ###

Name: Storefront
Version: 2.2.5
`

**Comment by jameskoster** [comment]
Seems to be working here: https://woodev.mystagingwebsite.com/product/woo-single-1/ 

I tested locally and it's working fine for me.

Could you provide some more info @hannahswain ? Are you seeing any errors in the console etc?

**Comment by hannahswain** [comment]
I just tested it again - it is working on the test site, I must not have scrolled far enough.  Sorry for the bother, @jameskoster !
