### ISSUE TITLE
Add to Cart button hides text with RTL language 

### ISSUE THREAD

**Issue by lindamork** [woocommerce/storefront-sticky-add-to-cart#19]
When a RTL language is activated (Hebrew in this case), the 'Add to Cart' button hides the "You're viewing: productname"  

![screen shot on 2018-06-14 at 13_01_48](https://user-images.githubusercontent.com/16885584/41436614-0d953330-6fd7-11e8-9712-ee1de22efbe9.png)

[Ticket 1203908](https://woothemes.zendesk.com/agent/tickets/1203908)

**Comment by tiagonoronha** [comment]
@lindamork this extension is now included in Storefront as of 2.3. 

Deactivate the extension and update to the latest version of Storefront.

Thanks!
